services:
  tunasse_app:
    container_name: tunasse_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./entrypoint.dev.sh
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      tunasse_db:
        condition: service_healthy
      tunasse_db_test:
        condition: service_healthy
    tty: true
    networks:
      - laraken_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/up" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  tunasse_db:
    container_name: tunasse_db
    image: mariadb:11.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laraken_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 5

  tunasse_db_test:
    container_name: tunasse_db_test
    image: mariadb:11.8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test_root
      MYSQL_DATABASE: laraken_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - db_test_data:/var/lib/mysql
    networks:
      - laraken_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  db_data:
  db_test_data:

networks:
  laraken_network:
    driver: bridge
