FROM dunglas/frankenphp:1.11.1-php8.4

ARG USER=appuser
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g ${GROUP_ID} ${USER} && \
    useradd -m -l -u ${USER_ID} -g ${USER} -s /bin/bash ${USER} && \
    usermod -aG sudo ${USER}

USER root

RUN apt-get update && apt-get install -y git unzip zip

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

RUN install-php-extensions \
    pcntl \
    pdo_mysql \
    intl \
    gd \
    zip \
    exif
    # Add other PHP extensions here...

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN mkdir -p /app && chown -R ${USER}:${USER} /app

USER ${USER}

WORKDIR /app

COPY --chown=${USER}:${USER} . .
